master:
    image: elasticsearch:1.5
    volumes:
        - ./data:/data
    ports:
        - "9200:9200"
        - "9300:9300"
    command: /usr/share/elasticsearch/bin/elasticsearch -Des.config=/data/master.yml

e1:
    image: elasticsearch:1.5
    volumes:
        - ./data:/data
    ports:
        - "9201:9200"
        - "9301:9300"
    command: /usr/share/elasticsearch/bin/elasticsearch -Des.config=/data/elasticsearch.yml

e2:
    image: elasticsearch:1.5
    volumes:
        - ./data:/data
    ports:
        - "9202:9200"
        - "9302:9300"
    command: /usr/share/elasticsearch/bin/elasticsearch -Des.config=/data/elasticsearch.yml

e3:
    image: elasticsearch:1.5
    volumes:
        - ./data:/data
    ports:
        - "9203:9200"
        - "9303:9300"
    command: /usr/share/elasticsearch/bin/elasticsearch -Des.config=/data/elasticsearch.yml

client:
    image: elasticsearch:1.5
    volumes:
        - ./data:/data
    ports:
        - "9205:9200"
        - "9305:9300"
    command: /usr/share/elasticsearch/bin/elasticsearch -Des.config=/data/client.yml

kb:
    build: ./kibana/
    ports:
        - "5601:5601"
    environment:
        _ ELASTICSEARCH_PORT_9200_TCP_PORT: 9200
        _ ELASTICSEARCH_PORT_9200_TCP_ADDR: http://client
        _ KIBANA_INDEX:  flights
    links:
        - client
