client:
    image: elasticsearch:1.5
    volumes:
        - ./data:/data
    ports:
        - "9200:9200"
        - "9300:9300"
    command: /usr/share/elasticsearch/bin/elasticsearch -Des.config=/data/client.yml

e1:
    image: elasticsearch:1.5
    volumes:
        - ./data:/data
    ports:
        - "9201:9200"
        - "9301:9300"
    command: /usr/share/elasticsearch/bin/elasticsearch -Des.config=/data/elasticsearch.yml

e2:
    image: elasticsearch:1.5
    volumes:
        - ./data:/data
    ports:
        - "9202:9200"
        - "9302:9300"
    command: /usr/share/elasticsearch/bin/elasticsearch -Des.config=/data/elasticsearch.yml

e3:
    image: elasticsearch:1.5
    volumes:
        - ./data:/data
    ports:
        - "9203:9200"
        - "9303:9300"
    command: /usr/share/elasticsearch/bin/elasticsearch -Des.config=/data/elasticsearch.yml

master:
    image: elasticsearch:1.5
    volumes:
        - ./data:/data
    ports:
        - "9205:9200"
        - "9305:9300"
    command: /usr/share/elasticsearch/bin/elasticsearch -Des.config=/data/master.yml

kb:
    build: ./kibana/
    volumes:
        - ./data:/data
    ports:
        - "5601:5601"
    links:
        - client
    command: /opt/kibana/bin/kibana --config /data/kibana.yml
